#ifndef LIBSLDOLE_GLOBAL_H
#define LIBSLDOLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBSLDOLE_LIBRARY)
#  define LIBSLDOLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBSLDOLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSLDOLE_GLOBAL_H
