/****************************************************************************
**
** Metadata for SwConst generated by dumpcpp from type library
** C:\Program Files\SolidWorks Corp\SolidWorks\swconst.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_SWCONST_NOINLINES
#include "sldconst.h"

using namespace SwConst;

